//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXCEPTION_MEAL_SHIFT
    {
        public long ExceptionMealShiftID { get; set; }
        public long ExceptionMealID { get; set; }
        public int ShiftID { get; set; }
        public int ExceptionQty { get; set; }
        public int ExceptionQtyUsed { get; set; }
    }
}
