//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUDIT
    {
        public long AuditID { get; set; }
        public string UserName { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string FunctionName { get; set; }
        public string Action { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
    }
}
