//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXCEPTION_MEAL_USED_PRODUCT
    {
        public long ExceptionMealUsedProductID { get; set; }
        public long ExceptionMealUsedID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    }
}
