//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FUNCTION
    {
        public string FunctionName { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string Path { get; set; }
        public string ModuleCode { get; set; }
        public int SortOrder { get; set; }
        public string IconURL { get; set; }
        public Nullable<short> RoleID { get; set; }
    }
}
