//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SCHEDULE_MENU
    {
        public long ScheduleMenuID { get; set; }
        public System.DateTime MealDate { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> UserModified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
