//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BROADCAST
    {
        public int BroadcastID { get; set; }
        public System.DateTime BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Message { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> UserModified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
