//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MENU
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public int MenuDay { get; set; }
    }
}
