//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string EmployeeCode { get; set; }
        public string ContractNo { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID1 { get; set; }
        public Nullable<int> PositionID2 { get; set; }
        public Nullable<int> PositionID3 { get; set; }
        public bool IsLeaveOut { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string Remarks { get; set; }
    }
}
