//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_ROHTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SPECIAL
    {
        public int SpecialID { get; set; }
        public System.DateTime SpecialDate { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
    }
}
